### ISSUE TITLE
Can't Install in 2.93.1

### ISSUE THREAD

**Issue by DFliyerz** [przemir/ApplyModifierForObjectWithShapeKeys#14]
I'm trying to install this addon in Blender 2.93.1, and have followed the directions of enabling developer extras and only installing the .py file, but it still doesn't show up in the addons or F3 menu.

**Comment by przemir** [comment]
Can't reproduce problem. Enabling developer extra is not necessary for Blender 2.93.1 (it was required for Blender 2.9). You can try to copy .py file to <blender>\2.93\scripts\addons\ .

**Comment by DFliyerz** [comment]
Solved, turns out I somehow downloaded the plugin as html rather than the actual script, whoops.
