### ISSUE TITLE
"Traceback" Errors when trying to use tool

### ISSUE THREAD

**Issue by SherbertDrgn** [przemir/ApplyModifierForObjectWithShapeKeys#15]
I am getting these errors when I try to run this tool. I have tried to use blender 2.92 2.93 and 2.93.1 and I get the same result with each
![image](https://user-images.githubusercontent.com/87282542/125209695-e3fd6a00-e257-11eb-8357-72dae7eb4229.png)

**Comment by przemir** [comment]
I have the same error when I am using this addon for object which does not have shape keys (dialog also lacks combobox in such situation). I fixed this case.
