### ISSUE TITLE
When running script, no shape keys are created

### ISSUE THREAD

**Issue by bayerlse** [przemir/ApplyModifierForObjectWithShapeKeys#18]
Hey there! 

When running the script, no shape keys are created, despite the modifier vanishes...
I used it on a mesh wit wave modifier.

Thanks!

**Comment by przemir** [comment]
Hey!

Could you open "Window -> Toogle System Console" and paste console log here?
It would be even better with new version of script, as I added some console logs concerning which shape key is handled.
