### ISSUE TITLE
It doesn't work properly

### ISSUE THREAD

**Issue by JinxLaJoker** [przemir/ApplyModifierForObjectWithShapeKeys#2]
when using the script it makes all the shape keys into there own mesh and when looking back onto the meth it deleted some of the shape keys

**Comment by przemir** [comment]
Deleted shape key or deleted shape key content?
I found that even without using script deleting last keyshape could change mesh. And solution (or rather hack-fix) to this is to change to edit mode and return to object mode. I have committed changes to script.
