### ISSUE TITLE
Fails to apply

### ISSUE THREAD

**Issue by InfernoDigital** [przemir/ApplyModifierForObjectWithShapeKeys#21]
Always fails with an error saying "blendshapes must have same number of vertices) and then makes 3 clones, 2 without the modifier and 1 still with, and the 1 with all the blendshapes is the one that didn't apply the modifier

**Comment by przemir** [comment]
Different shapekeys may end up with different number of vertices after applying modifiers. In that case joining such meshes is not possible.
Try to change/disable modifier options which may cause this (for example in 'mirror' modifier there is "Merge" option which causes to merge vertices close to each other - some vertices may be merged for one shapekey but not for the other one).

**Comment by fluffy-critter** [comment]
Is there any way to see how many vertices are on each blendshape? That would make it a lot easier to track down issues like these, where for example a tiny seam accidentally got added when setting up phonemes (which happens to me all the time).

**Comment by fluffy-critter** [comment]
Ah, I finally learned about the viewport statistics overlay. That made finding the blendshape with an accidental split easy.
