### ISSUE TITLE
Blender crashes upon hitting F3 key

### ISSUE THREAD

**Issue by ChrisMenning** [przemir/ApplyModifierForObjectWithShapeKeys#24]
After a fresh install of Blender 2.93.14 (on Windows 10 Home, build 19044.2486), installing the package, and enabling Developer extras, I press the F3 key to open the menu and Blender immediately crashes.

**Comment by przemir** [comment]
Generally solution is to disable "Developer extras". For some reason it crashes for Blender 2.93.14 (even with this addon disabled).
Enabling "Developer extras" was necessary for Blender 2.9, but since 2.91.2 is no longer needed.
