### ISSUE TITLE
The process is not completed when the function is applied

### ISSUE THREAD

**Issue by foxgenco** [przemir/ApplyModifierForObjectWithShapeKeys#25]
```
Error: Shape keys ended up with different number of vertices!
All shape keys needs to have the same number of vertices after modifier is applied.
Otherwise joining such shape keys will fail!
```

**Comment by przemir** [comment]
Different shapekeys may end up with different number of vertices after applying modifiers. In that case joining such meshes is not possible.
Try to change/disable modifier options which may cause this (for example in 'mirror' modifier there is "Merge" option which causes to merge vertices close to each other - some vertices may be merged for one shapekey but not for the other one).
