### ISSUE TITLE
Issue When "Relative To" Is Not The Basis

### ISSUE THREAD

**Issue by mfclinton** [przemir/ApplyModifierForObjectWithShapeKeys#26]
This script fails when the `Relative To` entry is not equal to the basis (IE: equal to another shape key index).

**Comment by przemir** [comment]
Solved.

Problem occured only when "Relative to" pointed to shape key later on the list. If shape key pointed to shape key before everything was ok. Basis is the first element on list so it always worked.

Ensuring name of each shape key was copied before any relative_key property solved problem.

**Comment by mfclinton** [comment]
Awesome! I was gonna try to fix it myself and make a PR but I couldn't figure out a good debugging setup 🤷

**Comment by przemir** [comment]
You can debug blender addons with PyCharm or PyDev if you have blender addon which allows debugging.

Here is something about it: [https://code.blender.org/2015/10/debugging-python-code-with-pycharm/](https://code.blender.org/2015/10/debugging-python-code-with-pycharm/)
