### ISSUE TITLE
code errors?

### ISSUE THREAD

**Issue by mossmutt7** [przemir/ApplyModifierForObjectWithShapeKeys#28]
it might be because im using 2.79 for a specific model. help?  
![image](https://github.com/przemir/ApplyModifierForObjectWithShapeKeys/assets/160300945/be83dbc6-f56a-4d66-98d2-3382bfc2da02)

**Comment by przemir** [comment]
Script in master branch is for new blender versions like Blender 4.0.2.
For blender 2.79 change branch to blender-2.79 .
