### ISSUE TITLE
Lagged Blender to hell after use until closing

### ISSUE THREAD

**Issue by ChimiChamo** [przemir/ApplyModifierForObjectWithShapeKeys#29]
After using this on an armature, it worked fine but then each action in blender seemed to take several seconds to do no matter what it was like switching between object and pose mode. This persisted until closing and re-opening blender. This might be due to the amount of shape keys (133).

**Comment by przemir** [comment]
Found out that script deleted copied objects but not meshes. Therefore after applying script there were multiple orphaned meshes which could cause memory usage increase and application slow down.

I updated script so it shouldn't be problem anymore.
