### ISSUE TITLE
Doesn't work with mirror modifier

### ISSUE THREAD

**Issue by seanking2919** [przemir/ApplyModifierForObjectWithShapeKeys#3]
I tried doing to apply a mirror modifier while the object I was working on still had shape keys. And apparently, it still gives me the error.

**Comment by przemir** [comment]
What about "Merge" and "Clipping" options inside Mirror modifier? Are they disabled? Merge option can create meshes with different number of vertices (for example in one shape two vertices are in the same position, but in the other one their location differ), and those meshes cannot be added as shapes later.

**Comment by seanking2919** [comment]
Merge is on and clipping is off. My apologies for the delay in the response @przemir

**Comment by przemir** [comment]
If different shapes end up with different number of vertices they cannot be joined together. Thats what is causing problem here.
Try disabling the merge option and then apply mirror modifier.

**Comment by seanking2919** [comment]
Tried disabling the merge option, but it didn't work.

**Comment by przemir** [comment]
I completely forgot to write how to use this addon. I updated readme file and added some screen. Did you press 'Apply' button in modifiers tab? I didn't change behaviour of this button.
To use this addon, press 'space' and choose 'Apply modifier for object with shape keys' action.

**Comment by seanking2919** [comment]
Ah, got it. Didn't understand that. My bad.
