### ISSUE TITLE
No modifiers recognized in Blender 2.8 despite existing

### ISSUE THREAD

**Issue by seanking2919** [przemir/ApplyModifierForObjectWithShapeKeys#4]
I tried out this plugin in Blender 2.8. And apparently, it doesn't recognize any modifiers, even though there is modifiers for the object. See screenshot: https://pic8.co/sh/pRtUqs.png

**Comment by przemir** [comment]
This plugin wasn't updated to work with blender 2.8. That being said there are right now 3 forks where script was changed to support blender 2.8.

https://github.com/naelstrof/ApplyModifierForObjectWithShapeKeys
https://github.com/Menithal/ApplyModifierForObjectWithShapeKeys
https://github.com/iszotic/ApplyModifierForObjectWithShapeKeys

**Comment by seanking2919** [comment]
Cool thx
