### ISSUE TITLE
Blender 2.9 update

### ISSUE THREAD

**Issue by NIZO0** [przemir/ApplyModifierForObjectWithShapeKeys#5]
Hi, I really appreciate your work ♥. Can you please update the code to work with blender version 2.9. 
![Screenshot (17)](https://user-images.githubusercontent.com/70943980/92455479-62b5f080-f1ca-11ea-98fe-ef85b3c1a0ac.png)

**Comment by przemir** [comment]
Hi! Addon should support blender 2.9 now.
Seems like "F3" search menu don't show operator in blender 2.9, unless "Developer Extras" is checked in "Edit -> Preferences -> Interface".
