### ISSUE TITLE
Feature Request: Mirror Shapekeys

### ISSUE THREAD

**Issue by DonWippo** [przemir/ApplyModifierForObjectWithShapeKeys#8]
If a Mesh has two identical named shapekeys for each Side with the Endings of .L and .R respectively it would be useful if the function did not create one symmetrical shapekey, but a seperate one for each side.

**Comment by przemir** [comment]
Sorry for late response. If I understand correctly, you want not only to apply mirror modifier, but also to clone shapekeys to match mirrored part. It is special usage which won't happen in any other modifer.

Newly added vertices would be assigned to different shapekey (you have to identify which vertices are mirrored which may be complicated if mirrored part overlap with original). If 'merge' option is checked some vertices may be assigned to both shapekeys as well.

It seems like lot of work. Propably it would be easier to clone object, multiply dimension by -1 for each shape, rename shapekeys, join objects, remove duplicated vertices.

Sorry, but I won't make this feature.
