### ISSUE TITLE
Cannot install to Blender 2.9

### ISSUE THREAD

**Issue by Vorked** [przemir/ApplyModifierForObjectWithShapeKeys#9]
When attempting to install to 2.9, it does not show up in Addon list. Is there a way to fix this on my end or would an update need to be made?

**Comment by Toxic-Cookie** [comment]
Also having the same issue.

**Comment by nizhuan-jjr** [comment]
![2021-01-26_224304](https://user-images.githubusercontent.com/3255986/105860513-a352c100-6028-11eb-8a2e-5c8dcaf4f9c9.png)
I've checked the Developer Extras.

![2021-01-26_224417](https://user-images.githubusercontent.com/3255986/105860556-abaafc00-6028-11eb-91f3-738bb78c6186.png)
The addon has been installed successfully.

![2021-01-26_224334](https://user-images.githubusercontent.com/3255986/105860594-b4033700-6028-11eb-9dab-e7df52e8f65c.png)
However, F3 can't find the script.

**Comment by Br4x** [comment]
same here :'(

**Comment by przemir** [comment]
Sorry for late response. It seems there are two issues here:

1) Missing addon in addon list for Blender 2.9:
Check 'Developer Extras' checkbox in "Edit -> Preferences -> Interface".
Btw. Blender 2.91.2 does not require this step anymore to show addons. 

2) Missing script method in F3 for Blender 2.91:
I have updated addon to support Blender 2.91.2. This should fix F3 missing script method problem.

**Comment by Br4x** [comment]
It doesn't work either 😭 
![Capture](https://user-images.githubusercontent.com/4102402/107523217-c9459d00-6bb4-11eb-8248-82a41f339863.PNG)

**Comment by TayouVR** [comment]
I have the same problem, nothing shows up in blender. blender reports successful installation, but no addon in list, no function in search. 
I am running blender 2.91.2 (hash: 5be9ef417703)
I have developer extras enabled too, just in case.
![image](https://user-images.githubusercontent.com/31988415/107583176-d7b6a780-6bfa-11eb-952e-1505744b1009.png)

**Comment by przemir** [comment]
You added addon as folder, when you need to add 'ApplyModifierForObjectWithShapeKeys.py' file alone.

**Comment by TayouVR** [comment]
okay, did that today thinking it might work, and yea.. it shows up, now i am just stuck with another problem....
![image](https://user-images.githubusercontent.com/31988415/107691520-d3969280-6cab-11eb-9b75-c1cddd33705d.png)
![image](https://user-images.githubusercontent.com/31988415/107691542-d8f3dd00-6cab-11eb-8752-d5ef9b0a0124.png)
should i open another issue?

**Comment by przemir** [comment]
Joining shape keys failed, probably due to different number of vertices. I updated addon to show error message in such case. 

Disable merge/clipping option in mirror modifier.
